export enum StructureType {
	Barracks = 'barracks',
	Warehouse = 'warehouse',
	Academy = 'academy',
	Bazaar = 'bazaar',
	CountingHouse = 'counting house',
	Forge = 'forge',
	Guildhall = 'guildhall',
	Hall = 'hall',
	Intelligencer = 'intelligencer',
	Monument = 'monument',
	Observatory = 'observatory',
	Quartermaster = 'quartermaster',
	Sanatorium = 'sanatorium',
	Scriptorium = 'scriptorium',
	Shipyard = 'shipyard',
	Tavern = 'tavern',
	Temple = 'temple',
	ThievesGuild = 'thieves guild',
	TrainingGround = 'training ground',
	WarRoom = 'war room',
	WizardTower = 'wizard tower'
}
